name: Mopidy
version: "1.0.0"
slug: mopidy
description: A music server that plays music from local storage, network resources, and the internet.
arch:
  - armv7
  - armhf
  - aarch64
  - amd64
  - i386
startup: "services"
init: false
ports:
  6680/tcp: 6680
map:
  - config
options: {}
schema: {}
