name: "Mopidy Add-On"
version: "1.0.0"
slug: "mopidy"
description: "Mopidy music server with Ingress support"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: "services"
boot: "auto"
ingress: true
ingress_port: 6680
panel_icon: "mdi:music-note"
panel_title: "Mopidy"
ports: {}
map:
  - config:rw
  - ssl:ro
  - media:rw
  - share:rw
  - addons:rw
  - data:rw
options: {}
schema: {}
