name: Mopidy
version: "1.0.0"
slug: mopidy
description: Mopidy music server for Home Assistant
arch:
  - amd64
  - armv7
  - aarch64
  - armhf
  - i386
startup: services
boot: auto
ingress: true
ingress_port: 8099
ingress_entry: /
ingress_stream: false
panel_icon: "mdi:music"
ports:
  6680/tcp: null
options: {}
schema: {}
