name: "VirtualHere Server"
version: "1.0.0"
slug: "virtualhere_server"
description: "VirtualHere USB Server to share USB devices over the network for Home Assistant"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
init: false
ports:
  7575/tcp: 7575
