name: Automatic Ripping Machine
version: "1.0"
slug: automatic_ripping_machine
description: "Home Assistant add-on to run Automatic Ripping Machine (ARM)"
arch:
  - aarch64
  - armv7
  - amd64
  - i386
  - armhf
startup: "application"
boot: "auto"
options: {}
schema: {}

# Allow the container privileged access to the host devices (updated format)
privileged:
  - true

# Use the correct format for devices: a list of paths
devices:
  - /dev
