name: "Automatic Ripping Machine"
version: "0.1.0"
slug: "automatic_ripping_machine"
description: "Barebones ARM configuration"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: "application"
boot: "auto"
options: {}
schema:
  devices:
    description: "List of paths to USB devices"
    type: "list"
    required: true
  log_level:
    description: "Log level"
    type: "select"
    options:
      - "debug"
      - "info"
      - "warning"
      - "error"
    default: "info"
  notify_method:
    description: "Notification method"
    type: "select"
    options:
      - "webhook"
    default: "webhook"
