name: Automatic Ripping Machine
version: "1.0"
slug: automatic_ripping_machine
description: "Home Assistant add-on to run Automatic Ripping Machine (ARM)"
arch:
  - aarch64
  - armv7
  - amd64
  - i386
  - armhf
startup: "application"
boot: "auto"
options: {}
schema: {}

# Ensure device access and privileges for hardware interaction
privileged:
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_RESOURCE
  - DAC_READ_SEARCH

# Provide access to /dev for the container to detect devices like DVD drives
devices:
  - /dev
