name: Automatic Ripping Machine
version: "1.0"
slug: automatic_ripping_machine
description: "Home Assistant add-on to run Automatic Ripping Machine (ARM)"
arch:
  - aarch64
  - armv7
  - amd64
  - i386
  - armhf
startup: "application"  # Updated from "delayed" to "application"
boot: "auto"
options: {}
schema: {}
