name: Automatic Ripping Machine
version: "1.0"
slug: automatic_ripping_machine
description: "Home Assistant add-on to run Automatic Ripping Machine (ARM)"
arch:
  - aarch64
  - amd64
  - armv7
startup: "services"
boot: "auto"
ingress: true
ingress_port: 0  # Dynamic ingress port assignment
panel_icon: "mdi:disc"
panel_title: "ARM Web UI"

# Networking optimizations
host_network: true  # Use host network to avoid Docker network issues

# Ensure device access and privileges for hardware interaction
privileged:
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_RESOURCE
  - DAC_READ_SEARCH

# Device access
devices:
  - /dev

# DBus access (if needed)
host_dbus: true
