name: Automatic Ripping Machine
version: "1.0"
slug: automatic_ripping_machine
description: "Home Assistant add-on to run Automatic Ripping Machine (ARM)"
arch:
  - aarch64
  - armv7
  - amd64
  - i386
  - armhf
startup: "services"
boot: "auto"
ingress: true  # Enable ingress for the web UI

timeout: 300  # Increase timeout to 5 minutes (300 seconds)

panel_icon: "mdi:disc"  # Icon to show in the sidebar
panel_title: "ARM Web UI"  # Title for the sidebar entry

ports:
  8080/tcp: 8080  # Expose port 8080 for the ARM Web UI

# Ensure device access and privileges for hardware interaction
privileged:
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_RESOURCE
  - DAC_READ_SEARCH

# Provide access to /dev for the container to detect devices like DVD drives
devices:
  - /dev
