# Use the official Automatic Ripping Machine Docker image as the base
FROM automaticrippingmachine/automatic-ripping-machine:latest

# No need to copy or use the run.sh script, as the ARM Docker image includes its own entrypoint.
